/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObsidianMasonryPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/masonry-view.ts
var import_obsidian3 = require("obsidian");

// src/modals.ts
var import_obsidian2 = require("obsidian");

// src/i18n.ts
var import_obsidian = require("obsidian");
var locales = {
  en: {
    "cmd.openMasonryView": "Open Masonry View for current folder",
    "cmd.toggleMasonryFolder": "Toggle masonry view for current folder",
    "menu.enableMasonry": "Enable Masonry View",
    "menu.disableMasonry": "Disable Masonry View",
    "menu.openMasonry": "Open in Masonry View",
    "menu.createPinBoard": "Create Pin Board here",
    "menu.pinToBoard": "Pin to board",
    "notice.boardCreated": (v) => `Pin board "${v == null ? void 0 : v.name}" created`,
    "notice.masonryDisabled": (v) => `Masonry View disabled for "${v == null ? void 0 : v.path}"`,
    "notice.masonryEnabled": (v) => `Masonry View enabled for "${v == null ? void 0 : v.path}"`,
    "notice.createBoardFailed": "Failed to create pin board",
    "sett.heading": "Masonry View",
    "sett.desc": 'Right-click a folder and choose "Open in Masonry View" to browse in Pinterest-like layout.',
    "sett.showNames": "Show file names under items",
    "sett.showNamesDesc": "Display the filename below each masonry card",
    "sett.showTags": "Show tags under items",
    "sett.showTagsDesc": "Display tags below each masonry card",
    "sett.gap": "Gap between items",
    "sett.gapDesc": "Spacing between cards in pixels",
    "sett.columns": "Column count",
    "sett.columnsDesc": "Number of masonry columns",
    "sett.noteMinH": "Note card min height",
    "sett.noteMinHDesc": "Minimum card height for notes (px)",
    "sett.noteMaxH": "Note card max height",
    "sett.noteMaxHDesc": "Maximum card height for notes (px) \u2014 content exceeding this is clipped",
    "sett.noteFontSize": "Note card font size",
    "sett.noteFontSizeDesc": "Font size for the note preview text (px)",
    "sett.folderCount": "Folders per row",
    "sett.folderCountDesc": "Number of folder cards in a single row",
    "sett.masonryFolders": "Masonry-enabled folders",
    "sett.none": "None",
    "sett.clearAssignments": "Clear all folder assignments",
    "sett.clearAssignmentsDesc": "Remove masonry view from all folders",
    "sett.clearBtn": "Clear All",
    "notice.settingsCleared": "Cleared all masonry folder settings",
    "view.tabBoard": (v) => `Board: ${v == null ? void 0 : v.name}`,
    "view.tabMasonry": (v) => `Masonry: ${v == null ? void 0 : v.path}`,
    "view.tabDefault": "Masonry View",
    "aria.back": "Back",
    "aria.forward": "Forward",
    "aria.editBoard": "Edit board file",
    "aria.tagCloud": "Tag cloud",
    "aria.assignTags": "Assign tags",
    "aria.pinSelected": "Pin selected to board",
    "placeholder.search": "Search name or tag\u2026",
    "placeholder.addTag": "add tag\u2026",
    "label.tags": "Tags: ",
    "label.tagCloud": "Tag Cloud",
    "label.noTags": "No tags in this folder",
    "label.emptyNote": "\u2014 empty note \u2014",
    "notice.folderNotFound": "Folder not found",
    "notice.noMatch": "No items match your search",
    "notice.boardEmpty": "This board is empty \u2014 pin some items!",
    "notice.folderEmpty": "This folder is empty",
    "notice.pinsRemoved": (v) => `Removed ${v == null ? void 0 : v.count} pin(s) from board`,
    "notice.permanentDeleted": (v) => `Permanently deleted ${v == null ? void 0 : v.count} item(s)`,
    "notice.movedToTrash": (v) => `Moved ${v == null ? void 0 : v.count} item(s) to trash`,
    "notice.selectFirst": "Select items first",
    "notice.noBoards": "No pin boards found. Right-click a folder \u2192 Create Pin Board here.",
    "notice.pinned": (v) => `Pinned to "${v == null ? void 0 : v.name}"`,
    "notice.pinnedCount": (v) => `Pinned ${v == null ? void 0 : v.count} item(s) to "${v == null ? void 0 : v.name}"`,
    "notice.moveFailed": "Move failed",
    "menu.open": "Open",
    "menu.pinToBoardShort": "Pin to board",
    "menu.assignTags": "Assign tags",
    "menu.removeFromBoard": "Remove from board",
    "menu.delete": "Delete",
    "modal.assignTagsTo": (v) => `Assign tags to ${v == null ? void 0 : v.count} item(s)`,
    "placeholder.tagsCsv": "Enter tags, comma-separated (e.g. concept, art, mood)",
    "btn.assign": "Assign",
    "notice.enterTag": "Enter at least one tag",
    "notice.tagsAssigned": (v) => `Assigned tags to ${v == null ? void 0 : v.count} item(s)`,
    "btn.close": "Close",
    "modal.addToPinBoard": "Add to Pin Board",
    "btn.pin": "Pin",
    "modal.createNewBoard": "Create New Board",
    "placeholder.boardName": "Board name\u2026",
    "btn.createAndPin": "Create & Pin",
    "notice.enterName": "Enter a name",
    "notice.boardCreatedWith": (v) => `Board "${v == null ? void 0 : v.name}" created with ${v == null ? void 0 : v.count} pin(s)`,
    "modal.imageCounter": (v) => `${v == null ? void 0 : v.name}  \u2014  ${v == null ? void 0 : v.idx} / ${v == null ? void 0 : v.total}`,
    "notice.pinnedToBoard": (v) => `Pinned ${v == null ? void 0 : v.count} item(s) to "${v == null ? void 0 : v.name}"`
  },
  ru: {
    "cmd.openMasonryView": "\u041E\u0442\u043A\u0440\u044B\u0442\u044C Masonry View \u0434\u043B\u044F \u0442\u0435\u043A\u0443\u0449\u0435\u0439 \u043F\u0430\u043F\u043A\u0438",
    "cmd.toggleMasonryFolder": "\u0412\u043A\u043B\u044E\u0447\u0438\u0442\u044C/\u0432\u044B\u043A\u043B\u044E\u0447\u0438\u0442\u044C Masonry View \u0434\u043B\u044F \u043F\u0430\u043F\u043A\u0438",
    "menu.enableMasonry": "\u0412\u0438\u0434 \u043F\u043B\u0438\u0442\u043A\u043E\u0439",
    "menu.disableMasonry": "\u041E\u0442\u043C\u0435\u043D\u0438\u0442\u044C \u0432\u0438\u0434 \u043F\u043B\u0438\u0442\u043A\u043E\u0439",
    "menu.openMasonry": "\u041E\u0442\u043A\u0440\u044B\u0442\u044C \u0432 Masonry View",
    "menu.createPinBoard": "\u0421\u043E\u0437\u0434\u0430\u0442\u044C \u0434\u043E\u0441\u043A\u0443 \u0437\u0430\u043C\u0435\u0442\u043E\u043A",
    "menu.pinToBoard": "\u041F\u0440\u0438\u043A\u0440\u0435\u043F\u0438\u0442\u044C \u043A \u0434\u043E\u0441\u043A\u0435",
    "notice.boardCreated": (v) => `\u0414\u043E\u0441\u043A\u0430 \xAB${v == null ? void 0 : v.name}\xBB \u0441\u043E\u0437\u0434\u0430\u043D\u0430`,
    "notice.masonryDisabled": (v) => `Masonry View \u0432\u044B\u043A\u043B\u044E\u0447\u0435\u043D \u0434\u043B\u044F \xAB${v == null ? void 0 : v.path}\xBB`,
    "notice.masonryEnabled": (v) => `Masonry View \u0432\u043A\u043B\u044E\u0447\u0451\u043D \u0434\u043B\u044F \xAB${v == null ? void 0 : v.path}\xBB`,
    "notice.createBoardFailed": "\u041D\u0435 \u0443\u0434\u0430\u043B\u043E\u0441\u044C \u0441\u043E\u0437\u0434\u0430\u0442\u044C \u0434\u043E\u0441\u043A\u0443",
    "sett.heading": "Masonry View",
    "sett.desc": "\u0429\u0451\u043B\u043A\u043D\u0438\u0442\u0435 \u043F\u0440\u0430\u0432\u043E\u0439 \u043A\u043D\u043E\u043F\u043A\u043E\u0439 \u043F\u043E \u043F\u0430\u043F\u043A\u0435 \u0438 \u0432\u044B\u0431\u0435\u0440\u0438\u0442\u0435 \xAB\u041E\u0442\u043A\u0440\u044B\u0442\u044C \u0432 Masonry View\xBB \u0434\u043B\u044F \u043F\u0440\u043E\u0441\u043C\u043E\u0442\u0440\u0430 \u0432 \u043F\u043B\u0438\u0442\u043E\u0447\u043D\u043E\u0439 \u0440\u0430\u0441\u043A\u043B\u0430\u0434\u043A\u0435.",
    "sett.showNames": "\u041F\u043E\u043A\u0430\u0437\u044B\u0432\u0430\u0442\u044C \u0438\u043C\u0435\u043D\u0430 \u0444\u0430\u0439\u043B\u043E\u0432",
    "sett.showNamesDesc": "\u041E\u0442\u043E\u0431\u0440\u0430\u0436\u0430\u0442\u044C \u0438\u043C\u044F \u0444\u0430\u0439\u043B\u0430 \u043F\u043E\u0434 \u043A\u0430\u0436\u0434\u043E\u0439 \u043A\u0430\u0440\u0442\u043E\u0447\u043A\u043E\u0439",
    "sett.showTags": "\u041F\u043E\u043A\u0430\u0437\u044B\u0432\u0430\u0442\u044C \u0442\u0435\u0433\u0438",
    "sett.showTagsDesc": "\u041E\u0442\u043E\u0431\u0440\u0430\u0436\u0430\u0442\u044C \u0442\u0435\u0433\u0438 \u043F\u043E\u0434 \u043A\u0430\u0436\u0434\u043E\u0439 \u043A\u0430\u0440\u0442\u043E\u0447\u043A\u043E\u0439",
    "sett.gap": "\u0420\u0430\u0441\u0441\u0442\u043E\u044F\u043D\u0438\u0435 \u043C\u0435\u0436\u0434\u0443 \u044D\u043B\u0435\u043C\u0435\u043D\u0442\u0430\u043C\u0438",
    "sett.gapDesc": "\u0420\u0430\u0441\u0441\u0442\u043E\u044F\u043D\u0438\u0435 \u043C\u0435\u0436\u0434\u0443 \u043A\u0430\u0440\u0442\u043E\u0447\u043A\u0430\u043C\u0438 \u0432 \u043F\u0438\u043A\u0441\u0435\u043B\u044F\u0445",
    "sett.columns": "\u041A\u043E\u043B\u0438\u0447\u0435\u0441\u0442\u0432\u043E \u043A\u043E\u043B\u043E\u043D\u043E\u043A",
    "sett.columnsDesc": "\u0427\u0438\u0441\u043B\u043E \u043A\u043E\u043B\u043E\u043D\u043E\u043A \u0432 \u043F\u043B\u0438\u0442\u043E\u0447\u043D\u043E\u0439 \u0440\u0430\u0441\u043A\u043B\u0430\u0434\u043A\u0435",
    "sett.noteMinH": "\u041C\u0438\u043D. \u0432\u044B\u0441\u043E\u0442\u0430 \u043A\u0430\u0440\u0442\u043E\u0447\u043A\u0438 \u0437\u0430\u043C\u0435\u0442\u043A\u0438",
    "sett.noteMinHDesc": "\u041C\u0438\u043D\u0438\u043C\u0430\u043B\u044C\u043D\u0430\u044F \u0432\u044B\u0441\u043E\u0442\u0430 \u043A\u0430\u0440\u0442\u043E\u0447\u043A\u0438 \u0437\u0430\u043C\u0435\u0442\u043A\u0438 (px)",
    "sett.noteMaxH": "\u041C\u0430\u043A\u0441. \u0432\u044B\u0441\u043E\u0442\u0430 \u043A\u0430\u0440\u0442\u043E\u0447\u043A\u0438 \u0437\u0430\u043C\u0435\u0442\u043A\u0438",
    "sett.noteMaxHDesc": "\u041C\u0430\u043A\u0441\u0438\u043C\u0430\u043B\u044C\u043D\u0430\u044F \u0432\u044B\u0441\u043E\u0442\u0430 \u043A\u0430\u0440\u0442\u043E\u0447\u043A\u0438 \u0437\u0430\u043C\u0435\u0442\u043A\u0438 (px)",
    "sett.noteFontSize": "\u0420\u0430\u0437\u043C\u0435\u0440 \u0448\u0440\u0438\u0444\u0442\u0430 \u0437\u0430\u043C\u0435\u0442\u043A\u0438",
    "sett.noteFontSizeDesc": "\u0420\u0430\u0437\u043C\u0435\u0440 \u0448\u0440\u0438\u0444\u0442\u0430 \u0442\u0435\u043A\u0441\u0442\u0430 \u0437\u0430\u043C\u0435\u0442\u043A\u0438 (px)",
    "sett.folderCount": "\u041F\u0430\u043F\u043E\u043A \u0432 \u0440\u044F\u0434\u0443",
    "sett.folderCountDesc": "\u041A\u043E\u043B\u0438\u0447\u0435\u0441\u0442\u0432\u043E \u043A\u0430\u0440\u0442\u043E\u0447\u0435\u043A \u043F\u0430\u043F\u043E\u043A \u0432 \u043E\u0434\u043D\u043E\u043C \u0440\u044F\u0434\u0443",
    "sett.masonryFolders": "\u041F\u0430\u043F\u043A\u0438 \u0441 Masonry View",
    "sett.none": "\u041D\u0435\u0442",
    "sett.clearAssignments": "\u041E\u0447\u0438\u0441\u0442\u0438\u0442\u044C \u0432\u0441\u0435 \u043D\u0430\u0437\u043D\u0430\u0447\u0435\u043D\u0438\u044F",
    "sett.clearAssignmentsDesc": "\u0423\u0431\u0440\u0430\u0442\u044C Masonry View \u0438\u0437 \u0432\u0441\u0435\u0445 \u043F\u0430\u043F\u043E\u043A",
    "sett.clearBtn": "\u041E\u0447\u0438\u0441\u0442\u0438\u0442\u044C \u0432\u0441\u0451",
    "notice.settingsCleared": "\u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 Masonry \u043E\u0447\u0438\u0449\u0435\u043D\u044B",
    "view.tabBoard": (v) => `\u0414\u043E\u0441\u043A\u0430: ${v == null ? void 0 : v.name}`,
    "view.tabMasonry": (v) => `Masonry: ${v == null ? void 0 : v.path}`,
    "view.tabDefault": "Masonry View",
    "aria.back": "\u041D\u0430\u0437\u0430\u0434",
    "aria.forward": "\u0412\u043F\u0435\u0440\u0451\u0434",
    "aria.editBoard": "\u0420\u0435\u0434\u0430\u043A\u0442\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u0444\u0430\u0439\u043B \u0434\u043E\u0441\u043A\u0438",
    "aria.tagCloud": "\u041E\u0431\u043B\u0430\u043A\u043E \u0442\u0435\u0433\u043E\u0432",
    "aria.assignTags": "\u041D\u0430\u0437\u043D\u0430\u0447\u0438\u0442\u044C \u0442\u0435\u0433\u0438",
    "aria.pinSelected": "\u041F\u0440\u0438\u043A\u0440\u0435\u043F\u0438\u0442\u044C \u0432\u044B\u0431\u0440\u0430\u043D\u043D\u043E\u0435 \u043A \u0434\u043E\u0441\u043A\u0435",
    "placeholder.search": "\u041F\u043E\u0438\u0441\u043A \u043F\u043E \u0438\u043C\u0435\u043D\u0438 \u0438\u043B\u0438 \u0442\u0435\u0433\u0443\u2026",
    "placeholder.addTag": "\u0434\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u0442\u0435\u0433\u2026",
    "label.tags": "\u0422\u0435\u0433\u0438: ",
    "label.tagCloud": "\u041E\u0431\u043B\u0430\u043A\u043E \u0442\u0435\u0433\u043E\u0432",
    "label.noTags": "\u041D\u0435\u0442 \u0442\u0435\u0433\u043E\u0432 \u0432 \u044D\u0442\u043E\u0439 \u043F\u0430\u043F\u043A\u0435",
    "label.emptyNote": "\u2014 \u043F\u0443\u0441\u0442\u0430\u044F \u0437\u0430\u043C\u0435\u0442\u043A\u0430 \u2014",
    "notice.folderNotFound": "\u041F\u0430\u043F\u043A\u0430 \u043D\u0435 \u043D\u0430\u0439\u0434\u0435\u043D\u0430",
    "notice.noMatch": "\u041D\u0438\u0447\u0435\u0433\u043E \u043D\u0435 \u043D\u0430\u0439\u0434\u0435\u043D\u043E",
    "notice.boardEmpty": "\u0414\u043E\u0441\u043A\u0430 \u043F\u0443\u0441\u0442\u0430 \u2014 \u043F\u0440\u0438\u043A\u0440\u0435\u043F\u0438\u0442\u0435 \u044D\u043B\u0435\u043C\u0435\u043D\u0442\u044B!",
    "notice.folderEmpty": "\u041F\u0430\u043F\u043A\u0430 \u043F\u0443\u0441\u0442\u0430",
    "notice.pinsRemoved": (v) => `\u0423\u0434\u0430\u043B\u0435\u043D\u043E ${v == null ? void 0 : v.count} \u0431\u0443\u043B\u0430\u0432\u043E\u043A \u0441 \u0434\u043E\u0441\u043A\u0438`,
    "notice.permanentDeleted": (v) => `\u041D\u0430\u0432\u0441\u0435\u0433\u0434\u0430 \u0443\u0434\u0430\u043B\u0435\u043D\u043E ${v == null ? void 0 : v.count} \u044D\u043B\u0435\u043C\u0435\u043D\u0442(\u043E\u0432)`,
    "notice.movedToTrash": (v) => `\u041F\u0435\u0440\u0435\u043C\u0435\u0449\u0435\u043D\u043E ${v == null ? void 0 : v.count} \u044D\u043B\u0435\u043C\u0435\u043D\u0442(\u043E\u0432) \u0432 \u043A\u043E\u0440\u0437\u0438\u043D\u0443`,
    "notice.selectFirst": "\u0421\u043D\u0430\u0447\u0430\u043B\u0430 \u0432\u044B\u0431\u0435\u0440\u0438\u0442\u0435 \u044D\u043B\u0435\u043C\u0435\u043D\u0442\u044B",
    "notice.noBoards": "\u0414\u043E\u0441\u043A\u0438 \u043D\u0435 \u043D\u0430\u0439\u0434\u0435\u043D\u044B. \u041D\u0430\u0436\u043C\u0438\u0442\u0435 \u043F\u0440\u0430\u0432\u043E\u0439 \u043A\u043D\u043E\u043F\u043A\u043E\u0439 \u043D\u0430 \u043F\u0430\u043F\u043A\u0443 \u2192 \u0421\u043E\u0437\u0434\u0430\u0442\u044C \u0434\u043E\u0441\u043A\u0443.",
    "notice.pinned": (v) => `\u041F\u0440\u0438\u043A\u0440\u0435\u043F\u043B\u0435\u043D\u043E \u043A \xAB${v == null ? void 0 : v.name}\xBB`,
    "notice.pinnedCount": (v) => `\u041F\u0440\u0438\u043A\u0440\u0435\u043F\u043B\u0435\u043D\u043E ${v == null ? void 0 : v.count} \u044D\u043B\u0435\u043C\u0435\u043D\u0442(\u043E\u0432) \u043A \xAB${v == null ? void 0 : v.name}\xBB`,
    "notice.moveFailed": "\u041D\u0435 \u0443\u0434\u0430\u043B\u043E\u0441\u044C \u043F\u0435\u0440\u0435\u043C\u0435\u0441\u0442\u0438\u0442\u044C",
    "menu.open": "\u041E\u0442\u043A\u0440\u044B\u0442\u044C",
    "menu.pinToBoardShort": "\u041F\u0440\u0438\u043A\u0440\u0435\u043F\u0438\u0442\u044C \u043A \u0434\u043E\u0441\u043A\u0435",
    "menu.assignTags": "\u041D\u0430\u0437\u043D\u0430\u0447\u0438\u0442\u044C \u0442\u0435\u0433\u0438",
    "menu.removeFromBoard": "\u0423\u0431\u0440\u0430\u0442\u044C \u0441 \u0434\u043E\u0441\u043A\u0438",
    "menu.delete": "\u0423\u0434\u0430\u043B\u0438\u0442\u044C",
    "modal.assignTagsTo": (v) => `\u041D\u0430\u0437\u043D\u0430\u0447\u0438\u0442\u044C \u0442\u0435\u0433\u0438 \u0434\u043B\u044F ${v == null ? void 0 : v.count} \u044D\u043B\u0435\u043C\u0435\u043D\u0442(\u043E\u0432)`,
    "placeholder.tagsCsv": "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0442\u0435\u0433\u0438 \u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043F\u044F\u0442\u0443\u044E (\u043D\u0430\u043F\u0440. \u0438\u0434\u0435\u044F, \u0438\u0441\u043A\u0443\u0441\u0441\u0442\u0432\u043E, \u043D\u0430\u0441\u0442\u0440\u043E\u0435\u043D\u0438\u0435)",
    "btn.assign": "\u041D\u0430\u0437\u043D\u0430\u0447\u0438\u0442\u044C",
    "notice.enterTag": "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0445\u043E\u0442\u044F \u0431\u044B \u043E\u0434\u0438\u043D \u0442\u0435\u0433",
    "notice.tagsAssigned": (v) => `\u0422\u0435\u0433\u0438 \u043D\u0430\u0437\u043D\u0430\u0447\u0435\u043D\u044B \u0434\u043B\u044F ${v == null ? void 0 : v.count} \u044D\u043B\u0435\u043C\u0435\u043D\u0442(\u043E\u0432)`,
    "btn.close": "\u0417\u0430\u043A\u0440\u044B\u0442\u044C",
    "modal.addToPinBoard": "\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u043D\u0430 \u0434\u043E\u0441\u043A\u0443",
    "btn.pin": "\u041F\u0440\u0438\u043A\u0440\u0435\u043F\u0438\u0442\u044C",
    "modal.createNewBoard": "\u0421\u043E\u0437\u0434\u0430\u0442\u044C \u043D\u043E\u0432\u0443\u044E \u0434\u043E\u0441\u043A\u0443",
    "placeholder.boardName": "\u041D\u0430\u0437\u0432\u0430\u043D\u0438\u0435 \u0434\u043E\u0441\u043A\u0438\u2026",
    "btn.createAndPin": "\u0421\u043E\u0437\u0434\u0430\u0442\u044C \u0438 \u043F\u0440\u0438\u043A\u0440\u0435\u043F\u0438\u0442\u044C",
    "notice.enterName": "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043D\u0430\u0437\u0432\u0430\u043D\u0438\u0435",
    "notice.boardCreatedWith": (v) => `\u0414\u043E\u0441\u043A\u0430 \xAB${v == null ? void 0 : v.name}\xBB \u0441\u043E\u0437\u0434\u0430\u043D\u0430 \u0441 ${v == null ? void 0 : v.count} \u0431\u0443\u043B\u0430\u0432\u043A\u043E\u0439(\u0430\u043C\u0438)`,
    "modal.imageCounter": (v) => `${v == null ? void 0 : v.name}  \u2014  ${v == null ? void 0 : v.idx} / ${v == null ? void 0 : v.total}`,
    "notice.pinnedToBoard": (v) => `\u041F\u0440\u0438\u043A\u0440\u0435\u043F\u043B\u0435\u043D\u043E ${v == null ? void 0 : v.count} \u044D\u043B\u0435\u043C\u0435\u043D\u0442(\u043E\u0432) \u043A \xAB${v == null ? void 0 : v.name}\xBB`
  }
};
var DEFAULT_LANG = "en";
function getUserLang() {
  try {
    const lang = (0, import_obsidian.getLanguage)().toLowerCase();
    if (locales[lang])
      return lang;
    const short = lang.substring(0, 2);
    if (locales[short])
      return short;
  } catch (e) {
  }
  return DEFAULT_LANG;
}
function t(key, vars) {
  var _a, _b, _c;
  const lang = getUserLang();
  const entry = (_c = (_a = locales[lang]) == null ? void 0 : _a[key]) != null ? _c : (_b = locales[DEFAULT_LANG]) == null ? void 0 : _b[key];
  if (typeof entry === "function")
    return entry(vars);
  if (typeof entry === "string") {
    if (!vars)
      return entry;
    let str = entry;
    for (const [k, v] of Object.entries(vars))
      str = str.replace(`{${k}}`, String(v));
    return str;
  }
  return key;
}

// src/modals.ts
var ImageViewModal = class extends import_obsidian2.Modal {
  constructor(app, plugin, images, startIdx, boardFile) {
    super(app);
    this.imgEls = [];
    this._activeIdx = 0;
    this._initialShow = true;
    this._boardFile = null;
    this._currentPath = "";
    this.scale = 1;
    this.fitScale = 1;
    this.fitToWindow = true;
    this.translateX = 0;
    this.translateY = 0;
    this._targetScale = 1;
    this._targetTranslateX = 0;
    this._targetTranslateY = 0;
    this._animId = null;
    this._navTimer = null;
    this.isDragging = false;
    this.dragMoved = false;
    this.dragStartX = 0;
    this.dragStartY = 0;
    this.dragTransX = 0;
    this.dragTransY = 0;
    this._onImgLoad = (e) => {
      const img = e.currentTarget;
      this.dimsEl.setText(`${img.naturalWidth}\xD7${img.naturalHeight}`);
      if (!this.fitToWindow) {
        img.style.width = `${img.naturalWidth}px`;
        img.style.height = `${img.naturalHeight}px`;
      }
      this._updateFitScale(img);
      this._updateZoomDisplay();
    };
    this._showContextMenu = (e) => {
      e.preventDefault();
      if (this.dragMoved)
        return;
      const menu = new import_obsidian2.Menu();
      menu.addItem(
        (item) => item.setTitle("\u041C\u0430\u0441\u0448\u0442\u0430\u0431 \u2192 100%").onClick(() => this._setZoom100())
      );
      menu.addItem(
        (item) => item.setTitle("\u0426\u0435\u043D\u0442\u0440\u043E\u0432\u0430\u0442\u044C \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435").onClick(() => this._centerImage())
      );
      menu.addItem(
        (item) => item.setTitle("\u0412\u043F\u0438\u0441\u0430\u0442\u044C \u0432 \u043E\u043A\u043D\u043E").setChecked(this.fitToWindow).onClick(() => this._toggleFitToWindow())
      );
      menu.addSeparator();
      menu.addItem(
        (item) => item.setTitle("\u041E\u0442\u043A\u0440\u044B\u0442\u044C \u0432 \u043F\u0440\u043E\u0432\u043E\u0434\u043D\u0438\u043A\u0435").setIcon("folder-open").onClick(() => this._openInExplorer())
      );
      if (this._boardFile) {
        menu.addItem(
          (item) => item.setTitle("\u0423\u0431\u0440\u0430\u0442\u044C \u0441 \u0434\u043E\u0441\u043A\u0438").setIcon("log-out").onClick(() => {
            void this._removeFromBoard();
          })
        );
      } else {
        menu.addItem(
          (item) => item.setTitle("\u0423\u0434\u0430\u043B\u0438\u0442\u044C \u0444\u0430\u0439\u043B").setIcon("trash-2").onClick(() => {
            void this._deleteFile();
          })
        );
      }
      menu.showAtMouseEvent(e);
    };
    this._onWheel = (e) => {
      e.preventDefault();
      const delta = e.deltaY > 0 ? -0.1 : 0.1;
      this._targetScale = Math.max(0.25, Math.min(6, this._targetScale + delta));
      this._startAnim();
    };
    this._onMouseDown = (e) => {
      if (e.button !== 2)
        return;
      e.preventDefault();
      this.isDragging = true;
      this.dragMoved = false;
      this.dragStartX = e.clientX;
      this.dragStartY = e.clientY;
      this.dragTransX = this.translateX;
      this.dragTransY = this.translateY;
      this.imgContainer.addClass("masonry-iv-grabbing");
    };
    this._onMouseMove = (e) => {
      if (!this.isDragging)
        return;
      this.dragMoved = true;
      this._targetTranslateX = this.dragTransX + (e.clientX - this.dragStartX);
      this._targetTranslateY = this.dragTransY + (e.clientY - this.dragStartY);
      this._startAnim();
    };
    this._onMouseUp = (e) => {
      if (e.button !== 2 || !this.isDragging)
        return;
      this.isDragging = false;
      this.imgContainer.removeClass("masonry-iv-grabbing");
    };
    this.plugin = plugin;
    this.images = images;
    this.curIdx = startIdx;
    this._boardFile = boardFile != null ? boardFile : null;
  }
  get _imgEl() {
    return this.imgEls[this._activeIdx];
  }
  onOpen() {
    var _a, _b, _c;
    const { contentEl } = this;
    contentEl.addClass("masonry-image-viewer");
    contentEl.empty();
    this.modalEl.addClass("masonry-image-modal");
    this.imgContainer = contentEl.createDiv({ cls: "masonry-iv-container" });
    this.imgEls[0] = this.imgContainer.createEl("img", { cls: "masonry-iv-img masonry-iv-img-active" });
    this.imgEls[1] = this.imgContainer.createEl("img", { cls: "masonry-iv-img masonry-iv-img-hidden" });
    for (const el of this.imgEls) {
      el.addEventListener("load", this._onImgLoad);
    }
    this.leftNav = contentEl.createDiv({ cls: "masonry-iv-nav masonry-iv-nav-left" });
    this.leftNav.setText("\u2039");
    this.leftNav.addEventListener("click", () => this.nav(-1));
    this.rightNav = contentEl.createDiv({ cls: "masonry-iv-nav masonry-iv-nav-right" });
    this.rightNav.setText("\u203A");
    this.rightNav.addEventListener("click", () => this.nav(1));
    const bottom = contentEl.createDiv({ cls: "masonry-iv-bottom" });
    this.nameEl = bottom.createSpan({ cls: "masonry-iv-name" });
    this.dimsEl = bottom.createSpan({ cls: "masonry-iv-dims" });
    this.zoomEl = bottom.createSpan({ cls: "masonry-iv-zoom" });
    bottom.createSpan({ cls: "masonry-iv-sep", text: "|" });
    const pinBtn = bottom.createEl("button", { cls: "masonry-iv-pin-btn" });
    (0, import_obsidian2.setIcon)(pinBtn, "pin");
    pinBtn.addEventListener("click", (e) => {
      const rect = pinBtn.getBoundingClientRect();
      const menu = new import_obsidian2.Menu();
      const boards = this.plugin.getPinBoards();
      for (const board of boards) {
        menu.addItem(
          (item) => item.setTitle(board.name.replace(/\.md$/i, "")).onClick(() => {
            void (async () => {
              await this.plugin.addToPinBoard(this._currentPath, board);
              new import_obsidian2.Notice(`\u041F\u0440\u0438\u043A\u0440\u0435\u043F\u043B\u0435\u043D\u043E \u043A ${board.name.replace(/\.md$/i, "")}`);
            })();
          })
        );
      }
      menu.addSeparator();
      menu.addItem(
        (item) => item.setTitle("\u0421\u043E\u0437\u0434\u0430\u0442\u044C \u0434\u043E\u0441\u043A\u0443").onClick(() => this._pinToBoard())
      );
      menu.showAtPosition({ x: rect.left, y: rect.bottom });
    });
    this._tagInputEl = bottom.createEl("input", {
      cls: "masonry-iv-tag-input",
      attr: { type: "text", placeholder: "\u0422\u0435\u0433..." }
    });
    this.tagsEl = bottom.createDiv({ cls: "masonry-iv-tags" });
    this._tagInputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        const val = this._tagInputEl.value.trim();
        if (val)
          void this._addTag(val);
      }
    });
    (_a = this.scope) == null ? void 0 : _a.register([], "ArrowLeft", () => {
      this.nav(-1);
      return false;
    });
    (_b = this.scope) == null ? void 0 : _b.register([], "ArrowRight", () => {
      this.nav(1);
      return false;
    });
    (_c = this.scope) == null ? void 0 : _c.register([], "Escape", () => {
      this.close();
      return false;
    });
    this.imgContainer.addEventListener("wheel", this._onWheel, { passive: false });
    this.imgContainer.addEventListener("mousedown", this._onMouseDown);
    this.imgContainer.addEventListener("contextmenu", (e) => e.preventDefault());
    activeDocument.addEventListener("mousemove", this._onMouseMove);
    activeDocument.addEventListener("mouseup", this._onMouseUp);
    this.show(this.curIdx);
    window.requestAnimationFrame(() => {
      this.modalEl.addClass("masonry-iv-visible");
      const bg = this.modalEl.previousElementSibling;
      if (bg)
        bg.addClass("masonry-iv-bg-visible");
    });
  }
  close() {
    this.modalEl.removeClass("masonry-iv-visible");
    const bg = this.modalEl.previousElementSibling;
    if (bg)
      bg.removeClass("masonry-iv-bg-visible");
    window.setTimeout(() => super.close(), 300);
  }
  onClose() {
    if (this._animId !== null)
      cancelAnimationFrame(this._animId);
    if (this._navTimer !== null)
      window.clearTimeout(this._navTimer);
    activeDocument.removeEventListener("mousemove", this._onMouseMove);
    activeDocument.removeEventListener("mouseup", this._onMouseUp);
    this.contentEl.empty();
  }
  _updateFitScale(img) {
    const el = img != null ? img : this._imgEl;
    if (!this.fitToWindow || !el.naturalWidth) {
      this.fitScale = 1;
      return;
    }
    const cw = this.imgContainer.clientWidth;
    const ch = this.imgContainer.clientHeight;
    const sx = cw / el.naturalWidth;
    const sy = ch / el.naturalHeight;
    this.fitScale = Math.min(sx, sy);
  }
  _updateZoomDisplay() {
    const pct = Math.round(this.fitScale * this.scale * 100);
    this.zoomEl.setText(`${pct}%`);
  }
  _setZoom100() {
    this.fitToWindow = false;
    this._imgEl.style.width = `${this._imgEl.naturalWidth}px`;
    this._imgEl.style.height = `${this._imgEl.naturalHeight}px`;
    this._imgEl.style.removeProperty("object-fit");
    this._targetScale = 1;
    this._targetTranslateX = 0;
    this._targetTranslateY = 0;
    this.fitScale = 1;
    this._startAnim();
  }
  _centerImage() {
    this._targetTranslateX = 0;
    this._targetTranslateY = 0;
    this._startAnim();
  }
  _toggleFitToWindow() {
    this.fitToWindow = !this.fitToWindow;
    if (this.fitToWindow) {
      this._imgEl.style.removeProperty("object-fit");
      this._imgEl.style.removeProperty("width");
      this._imgEl.style.removeProperty("height");
      this._targetScale = 1;
      this._targetTranslateX = 0;
      this._targetTranslateY = 0;
      this._updateFitScale();
    } else {
      this._imgEl.style.width = `${this._imgEl.naturalWidth}px`;
      this._imgEl.style.height = `${this._imgEl.naturalHeight}px`;
      this._imgEl.style.removeProperty("object-fit");
      this.fitScale = 1;
      this._targetScale = 1;
      this._targetTranslateX = 0;
      this._targetTranslateY = 0;
    }
    this._startAnim();
  }
  _renderTags() {
    const tags = this.plugin.getItemTags ? this.plugin.getItemTags(this._currentPath) : [];
    this.tagsEl.empty();
    for (const tag of tags) {
      const chip = this.tagsEl.createSpan({ cls: "masonry-chip" });
      chip.createSpan({ cls: "masonry-chip-label", text: `#${tag}` });
      const del = chip.createSpan({ cls: "masonry-chip-x", text: "\xD7" });
      del.addEventListener("click", (e) => {
        e.stopPropagation();
        void this._removeTag(tag);
      });
    }
  }
  async _addTag(tag) {
    const tags = this.plugin.getItemTags ? this.plugin.getItemTags(this._currentPath) : [];
    if (!tags.includes(tag)) {
      await this.plugin.setItemTags(this._currentPath, [...tags, tag]);
    }
    this._renderTags();
    this._tagInputEl.value = "";
    this._tagInputEl.focus();
  }
  async _removeTag(tag) {
    const tags = this.plugin.getItemTags ? this.plugin.getItemTags(this._currentPath) : [];
    await this.plugin.setItemTags(this._currentPath, tags.filter((t2) => t2 !== tag));
    this._renderTags();
  }
  _pinToBoard() {
    const boards = this.plugin.getPinBoards();
    new PinSelectModal(this.app, this.plugin, boards, [this._currentPath]).open();
  }
  _focusTagInput() {
    var _a;
    (_a = this._tagInputEl) == null ? void 0 : _a.focus();
  }
  _openInExplorer() {
    const file = this.app.vault.getAbstractFileByPath(this._currentPath);
    if (!file || !(file instanceof import_obsidian2.TFile))
      return;
    try {
      const adapter = this.app.vault.adapter;
      const fullPath = adapter.getFullPath(file.path);
      const electron = window.require("electron");
      electron.shell.showItemInFolder(fullPath);
    } catch (e) {
      console.error("Failed to open in explorer", e);
    }
  }
  async _removeFromBoard() {
    if (!this._boardFile)
      return;
    await this.app.fileManager.processFrontMatter(this._boardFile, (fm) => {
      const data = fm;
      if (Array.isArray(data.pins)) {
        data.pins = data.pins.filter((pin) => pin !== this._currentPath);
      }
    });
    new import_obsidian2.Notice("\u0423\u0431\u0440\u0430\u043D\u043E \u0441 \u0434\u043E\u0441\u043A\u0438");
    this.close();
  }
  async _deleteFile() {
    const file = this.app.vault.getAbstractFileByPath(this._currentPath);
    if (!file || !(file instanceof import_obsidian2.TFile))
      return;
    await this.app.fileManager.trashFile(file);
    new import_obsidian2.Notice("\u0424\u0430\u0439\u043B \u043F\u0435\u0440\u0435\u043C\u0435\u0449\u0451\u043D \u0432 \u043A\u043E\u0440\u0437\u0438\u043D\u0443");
    this.close();
  }
  _applyTransform() {
    this._imgEl.style.transform = `translate(${this.translateX}px, ${this.translateY}px) scale(${this.scale})`;
    this._updateZoomDisplay();
  }
  _startAnim() {
    if (this._animId !== null)
      return;
    this._animId = window.requestAnimationFrame(() => this._animate());
  }
  _animate() {
    const lerpSpeed = this.isDragging ? 0.35 : 0.18;
    this.scale += (this._targetScale - this.scale) * lerpSpeed;
    this.translateX += (this._targetTranslateX - this.translateX) * lerpSpeed;
    this.translateY += (this._targetTranslateY - this.translateY) * lerpSpeed;
    this._applyTransform();
    const done = Math.abs(this.scale - this._targetScale) < 1e-3 && Math.abs(this.translateX - this._targetTranslateX) < 0.5 && Math.abs(this.translateY - this._targetTranslateY) < 0.5;
    if (done) {
      this.scale = this._targetScale;
      this.translateX = this._targetTranslateX;
      this.translateY = this._targetTranslateY;
      this._applyTransform();
      this._animId = null;
    } else {
      this._animId = window.requestAnimationFrame(() => this._animate());
    }
  }
  _resetZoom() {
    this._targetScale = 1;
    this._targetTranslateX = 0;
    this._targetTranslateY = 0;
    this.scale = 1;
    this.translateX = 0;
    this.translateY = 0;
    this._applyTransform();
  }
  nav(dir) {
    const next = this.curIdx + dir;
    if (next >= 0 && next < this.images.length) {
      this.curIdx = next;
      this.show(next);
    }
  }
  show(idx) {
    const item = this.images[idx];
    if (!item)
      return;
    const file = this.app.vault.getAbstractFileByPath(item.path);
    if (!(file instanceof import_obsidian2.TFile))
      return;
    this._currentPath = item.path;
    if (this._navTimer !== null) {
      window.clearTimeout(this._navTimer);
      this._navTimer = null;
    }
    if (this._initialShow) {
      this._initialShow = false;
      this.imgEls[0].setAttr("src", this.app.vault.getResourcePath(file));
      this.nameEl.setText(item.name);
      this._renderTags();
      this.dimsEl.setText("");
      this.zoomEl.setText("");
      this.leftNav.toggleClass("masonry-iv-hidden", idx === 0);
      this.rightNav.toggleClass("masonry-iv-hidden", idx === this.images.length - 1);
      this._resetZoom();
      return;
    }
    const nextIdx = 1 - this._activeIdx;
    const prev = this.imgEls[this._activeIdx];
    const next = this.imgEls[nextIdx];
    next.style.transform = prev.style.transform || "";
    next.style.width = prev.style.width || "";
    next.style.height = prev.style.height || "";
    next.style.objectFit = prev.style.objectFit || "";
    next.setAttr("src", this.app.vault.getResourcePath(file));
    this.leftNav.toggleClass("masonry-iv-hidden", idx === 0);
    this.rightNav.toggleClass("masonry-iv-hidden", idx === this.images.length - 1);
    prev.addClass("masonry-iv-img-hidden");
    prev.removeClass("masonry-iv-img-active");
    next.removeClass("masonry-iv-img-hidden");
    next.addClass("masonry-iv-img-active");
    this._activeIdx = nextIdx;
    this._renderTags();
    const textEls = [this.nameEl, this.dimsEl, this.zoomEl];
    for (const el of textEls) {
      el.addClass("masonry-iv-text-fadeout");
    }
    this._navTimer = window.setTimeout(() => {
      this.nameEl.setText(item.name);
      for (const el of textEls) {
        el.removeClass("masonry-iv-text-fadeout");
        el.addClass("masonry-iv-text-fadein");
      }
      this._navTimer = window.setTimeout(() => {
        this._navTimer = null;
        for (const el of textEls)
          el.removeClass("masonry-iv-text-fadein");
      }, 120);
    }, 80);
  }
};
var PinSelectModal = class extends import_obsidian2.Modal {
  constructor(app, plugin, boards, paths) {
    super(app);
    this.plugin = plugin;
    this.boards = boards;
    this.paths = paths;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("masonry-pin-modal");
    contentEl.empty();
    contentEl.createEl("h2", { text: t("modal.addToPinBoard") });
    const row = contentEl.createDiv({ cls: "masonry-pin-select-row" });
    const select = row.createEl("select", { cls: "masonry-pin-select" });
    for (const board of this.boards) {
      select.createEl("option", {
        text: board.name.replace(/\.md$/i, ""),
        value: board.path
      });
    }
    const pinBtn = row.createEl("button", { cls: "mod-cta" });
    (0, import_obsidian2.setIcon)(pinBtn, "pin");
    pinBtn.createSpan({ text: " " + t("btn.pin") });
    pinBtn.addEventListener("click", () => {
      void (async () => {
        const selectedPath = select.value;
        const board = this.boards.find((b) => b.path === selectedPath);
        if (!board)
          return;
        for (const p of this.paths) {
          await this.plugin.addToPinBoard(p, board);
        }
        new import_obsidian2.Notice(t("notice.pinnedToBoard", { count: this.paths.length, name: board.name.replace(/\.md$/i, "") }));
        this.close();
      })();
    });
    contentEl.createEl("hr");
    const createSec = contentEl.createDiv({ cls: "masonry-pin-create" });
    createSec.createEl("h3", { text: t("modal.createNewBoard") });
    const input = createSec.createEl("input", {
      cls: "masonry-pin-name-input",
      attr: { placeholder: t("placeholder.boardName"), type: "text" }
    });
    const createBtn = createSec.createEl("button", { text: t("btn.createAndPin") });
    createBtn.addEventListener("click", () => {
      void (async () => {
        const name = input.value.trim();
        if (!name) {
          new import_obsidian2.Notice(t("notice.enterName"));
          return;
        }
        const file = await this.plugin.createPinBoard(name);
        if (!file)
          return;
        for (const p of this.paths) {
          await this.plugin.addToPinBoard(p, file);
        }
        new import_obsidian2.Notice(t("notice.boardCreatedWith", { name, count: this.paths.length }));
        this.close();
      })();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/masonry-view.ts
var VIEW_TYPE_MASONRY = "obsidian-masonry-view";
var IMAGE_EXTS = /* @__PURE__ */ new Set(["png", "jpg", "jpeg", "gif", "svg", "webp", "bmp", "ico"]);
var MasonryView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this._dragHandlers = null;
    this.currentPath = "";
    this.history = [];
    this.historyIdx = -1;
    this.items = [];
    this.selected = /* @__PURE__ */ new Set();
    this.searchQuery = "";
    this.lastSelectedEl = null;
    // board mode
    this.isBoardView = false;
    this.boardFile = null;
    this.tagFreq = /* @__PURE__ */ new Map();
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_MASONRY;
  }
  getDisplayText() {
    if (this.isBoardView && this.boardFile)
      return t("view.tabBoard", { name: this.boardFile.name.replace(/\.md$/i, "") });
    return this.currentPath ? t("view.tabMasonry", { path: this.currentPath }) : t("view.tabDefault");
  }
  getIcon() {
    return "grid-3x3";
  }
  async onOpen() {
    var _a, _b;
    const { containerEl: c } = this;
    c.empty();
    c.addClass("masonry-root");
    this.buildHeader(c);
    this.gridWrapper = c.createDiv({ cls: "masonry-grid-wrapper" });
    this.setupDragDrop();
    (_a = this.scope) == null ? void 0 : _a.register(["Mod", "Shift"], "Backspace", () => {
      void this.deleteSelected(true);
      return false;
    });
    (_b = this.scope) == null ? void 0 : _b.register([], "Delete", (e) => {
      if (e.ctrlKey || e.metaKey)
        void this.deleteSelected(true);
      else
        void this.deleteSelected(false);
      return false;
    });
    if (this.currentPath)
      await this.loadFolderOrBoard(this.currentPath);
  }
  // One-time drag-drop setup — document-level capture to intercept before Obsidian
  setupDragDrop() {
    const doc = activeDocument;
    let lastDragTarget = null;
    const isMasonryTarget = (e) => {
      var _a;
      return !!((_a = e.target) == null ? void 0 : _a.closest(".masonry-grid-wrapper"));
    };
    const isNavTitle = (e) => {
      var _a, _b;
      return (_b = (_a = e.target) == null ? void 0 : _a.closest(".nav-file-title")) != null ? _b : null;
    };
    const getSrc = (e) => {
      const dt = e.dataTransfer;
      if (!dt)
        return "";
      const plain = dt.getData("text/plain");
      if (plain) {
        const txt = plain.trim();
        const obsMatch = txt.match(/obsidian:\/\/open\?.*?[&?]file=([^&]+)/);
        if (obsMatch)
          return decodeURIComponent(obsMatch[1]).replace(/\\/g, "/");
        return txt.replace(/\\/g, "/");
      }
      const uri = dt.getData("text/uri-list");
      if (uri) {
        const decoded = decodeURI(uri.replace(/^file:\/\/\//i, "").replace(/^file:\/\//i, ""));
        return decoded.trim().replace(/\\/g, "/");
      }
      return "";
    };
    const resolvePath = (raw) => {
      var _a, _b;
      const tryPath = (p) => {
        const file = this.app.vault.getAbstractFileByPath(p);
        return file ? file.path : null;
      };
      let found = tryPath(raw);
      if (found)
        return found;
      if (!raw.match(/\.\w+$/)) {
        found = tryPath(raw + ".md");
        if (found)
          return found;
      }
      const adapter = this.app.vault.adapter;
      const vaultPath = ((_a = adapter.getFullPath) == null ? void 0 : _a.call(adapter, "/")) || "";
      if (vaultPath) {
        const norm = String(vaultPath).replace(/\\/g, "/").replace(/\/$/, "");
        const tryRel = (rel) => {
          const f = this.app.vault.getAbstractFileByPath(rel);
          return f ? f.path : null;
        };
        if (raw.startsWith(norm + "/")) {
          const rel = raw.slice(norm.length + 1);
          found = tryRel(rel);
          if (found)
            return found;
          if (!rel.match(/\.\w+$/)) {
            found = tryRel(rel + ".md");
            if (found)
              return found;
          }
        }
      }
      const name = ((_b = raw.split("/").pop()) == null ? void 0 : _b.split("\\").pop()) || "";
      const all = this.app.vault.getAllLoadedFiles();
      const byName = all.filter((f) => f.name === name);
      if (byName.length === 1)
        return byName[0].path;
      if (!name.match(/\.\w+$/)) {
        const exactMd = all.filter((f) => f.name === name + ".md");
        if (exactMd.length === 1)
          return exactMd[0].path;
      }
      const bySuffix = all.filter((f) => f.path.endsWith("/" + name));
      if (bySuffix.length === 1)
        return bySuffix[0].path;
      return raw;
    };
    const cleanBoardMarkers = () => {
      doc.querySelectorAll(".masonry-drop-board").forEach((el) => el.removeClass("masonry-drop-board"));
      doc.querySelectorAll(".masonry-drop-file-exp").forEach((el) => el.removeClass("masonry-drop-file-exp"));
    };
    const onDragOver = (e) => {
      if (isMasonryTarget(e)) {
        e.preventDefault();
        e.stopPropagation();
        const card = e.target.closest(".masonry-card");
        if (!card)
          return;
        if (lastDragTarget === card)
          return;
        if (lastDragTarget)
          lastDragTarget.removeClass("masonry-drop-board");
        lastDragTarget = null;
        const path2 = card.getAttr("data-path");
        if (!path2)
          return;
        const file2 = this.app.vault.getAbstractFileByPath(path2);
        if (file2 instanceof import_obsidian3.TFolder) {
          card.addClass("masonry-drop-board");
          lastDragTarget = card;
        } else if (file2 instanceof import_obsidian3.TFile && this.plugin.isPinBoard(file2)) {
          card.addClass("masonry-drop-board");
          lastDragTarget = card;
        }
        return;
      }
      const navTitle = isNavTitle(e);
      if (!navTitle)
        return;
      const path = navTitle.getAttr("data-path");
      if (!path)
        return;
      const file = this.app.vault.getAbstractFileByPath(path);
      if (file instanceof import_obsidian3.TFile && this.plugin.isPinBoard(file)) {
        e.preventDefault();
        e.stopPropagation();
        navTitle.addClass("masonry-drop-file-exp");
      }
    };
    const onDragLeave = () => {
      cleanBoardMarkers();
      lastDragTarget = null;
    };
    const onDrop = async (e) => {
      var _a;
      const src = getSrc(e);
      if (!src)
        return;
      const multiRaw = (_a = e.dataTransfer) == null ? void 0 : _a.getData("text/x-masonry-items");
      const rawPaths = multiRaw ? JSON.parse(multiRaw) : [src];
      const paths = rawPaths.map(resolvePath).filter(Boolean);
      if (!paths.length)
        return;
      if (isMasonryTarget(e)) {
        e.preventDefault();
        e.stopPropagation();
        cleanBoardMarkers();
        const targetCard = e.target.closest(".masonry-card");
        const targetPath2 = (targetCard == null ? void 0 : targetCard.getAttr("data-path")) || this.currentPath;
        if (!targetPath2)
          return;
        for (const p of paths)
          await this.handleDropOnFolder(p, targetPath2);
        await this.loadFolderOrBoard(this.currentPath);
        return;
      }
      const navTitle = isNavTitle(e);
      if (!navTitle)
        return;
      const targetPath = navTitle.getAttr("data-path");
      if (!targetPath)
        return;
      const file = this.app.vault.getAbstractFileByPath(targetPath);
      if (file instanceof import_obsidian3.TFile && this.plugin.isPinBoard(file)) {
        e.preventDefault();
        e.stopPropagation();
        cleanBoardMarkers();
        for (const p of paths) {
          await this.plugin.addToPinBoard(p, file);
        }
        new import_obsidian3.Notice(t("notice.pinned", { name: file.name.replace(/\.md$/i, "") }));
        await this.loadFolderOrBoard(this.currentPath);
      }
    };
    const opts = { capture: true };
    doc.addEventListener("dragover", onDragOver, opts);
    doc.addEventListener("dragleave", onDragLeave, opts);
    doc.addEventListener("drop", onDrop, opts);
    this._dragHandlers = { dragover: onDragOver, dragleave: onDragLeave, drop: onDrop };
  }
  async onClose() {
    this.containerEl.empty();
    if (this._dragHandlers) {
      const doc = activeDocument;
      for (const [evt, fn] of Object.entries(this._dragHandlers)) {
        doc.removeEventListener(evt, fn, { capture: true });
      }
    }
  }
  getState() {
    return { folderPath: this.currentPath, history: this.history, historyIdx: this.historyIdx, isBoardView: this.isBoardView };
  }
  async setState(state, result) {
    var _a;
    const path = state.folderPath;
    if (path) {
      this.currentPath = path;
      this.history = state.history || [];
      this.historyIdx = (_a = state.historyIdx) != null ? _a : -1;
      this.isBoardView = state.isBoardView || false;
      await this.loadFolderOrBoard(path);
    }
  }
  // ── entry point ─────────────────────────────────────────
  async loadFolderOrBoard(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (file instanceof import_obsidian3.TFile && file.extension === "md" && this.plugin.isPinBoard(file)) {
      await this.loadPinBoard(file);
    } else {
      await this.loadFolder(path);
    }
  }
  // ── header ──────────────────────────────────────────────
  buildHeader(c) {
    this.headerEl = c.createDiv({ cls: "masonry-header" });
    const row1 = this.headerEl.createDiv({ cls: "masonry-hrow" });
    const nav = row1.createDiv({ cls: "masonry-nav" });
    this.backBtn = nav.createEl("button", { cls: "masonry-nav-btn", attr: { "aria-label": t("aria.back") } });
    (0, import_obsidian3.setIcon)(this.backBtn, "arrow-left");
    this.backBtn.addEventListener("click", () => this.goBack());
    this.fwdBtn = nav.createEl("button", { cls: "masonry-nav-btn", attr: { "aria-label": t("aria.forward") } });
    (0, import_obsidian3.setIcon)(this.fwdBtn, "arrow-right");
    this.fwdBtn.addEventListener("click", () => this.goForward());
    const sc = row1.createDiv({ cls: "masonry-search" });
    const searchIcon = sc.createSpan({ cls: "masonry-search-icon" });
    (0, import_obsidian3.setIcon)(searchIcon, "search");
    this.searchEl = sc.createEl("input", {
      cls: "masonry-search-input",
      attr: { placeholder: t("placeholder.search"), type: "text" }
    });
    this.searchEl.addEventListener("input", () => {
      this.searchQuery = this.searchEl.value;
      this.render();
    });
    this.searchEl.addEventListener("keydown", (e) => {
      if (e.key === "Escape") {
        this.searchEl.value = "";
        this.searchQuery = "";
        this.render();
      }
    });
    this.pathEl = row1.createDiv({ cls: "masonry-path" });
    this.editBoardBtnEl = row1.createEl("button", {
      cls: "masonry-action-btn masonry-edit-board-btn",
      attr: { "aria-label": t("aria.editBoard") }
    });
    (0, import_obsidian3.setIcon)(this.editBoardBtnEl, "pencil");
    this.editBoardBtnEl.addClass("masonry-hide");
    this.editBoardBtnEl.addEventListener("click", () => {
      void this.editCurrentBoard();
    });
    const actions = row1.createDiv({ cls: "masonry-actions" });
    this.tagCloudBtnEl = actions.createEl("button", {
      cls: "masonry-action-btn",
      attr: { "aria-label": t("aria.tagCloud") }
    });
    (0, import_obsidian3.setIcon)(this.tagCloudBtnEl, "hash");
    this.tagCloudBtnEl.addEventListener("click", () => this.toggleTagCloud());
    const tagBtn = actions.createEl("button", {
      cls: "masonry-action-btn",
      attr: { "aria-label": t("aria.assignTags") }
    });
    (0, import_obsidian3.setIcon)(tagBtn, "tag");
    tagBtn.addEventListener("click", () => this.focusTagInput());
    const pinBtn = actions.createEl("button", {
      cls: "masonry-action-btn",
      attr: { "aria-label": t("aria.pinSelected") }
    });
    (0, import_obsidian3.setIcon)(pinBtn, "pin");
    pinBtn.addEventListener("click", () => {
      void this.showPinModal();
    });
    this.tagBarEl = this.headerEl.createDiv({ cls: "masonry-tag-bar" });
    this.tagBarEl.addClass("masonry-hide");
    this.tagBarEl.createSpan({ cls: "masonry-tag-label", text: t("label.tags") });
    this.tagChipsEl = this.tagBarEl.createDiv({ cls: "masonry-tag-chips" });
    this.tagInputEl = this.tagBarEl.createEl("input", {
      cls: "masonry-tag-input",
      attr: { placeholder: t("placeholder.addTag"), type: "text" }
    });
    this.tagInputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" || e.key === ",") {
        e.preventDefault();
        void this.addTagFromInput();
      } else if (e.key === "Backspace" && this.tagInputEl.value === "") {
        const chips = this.getCurrentChips();
        if (chips.length > 0)
          void this.removeTagAndSave(chips[chips.length - 1]);
      }
    });
    this.tagCloudEl = this.headerEl.createDiv({ cls: "masonry-tag-cloud" });
    this.tagCloudEl.addClass("masonry-hide");
  }
  // ── tag: auto-save on every change ──────────────────────
  getCurrentChips() {
    const tags = [];
    this.tagChipsEl.querySelectorAll(".masonry-chip").forEach((el) => {
      const label = el.querySelector(".masonry-chip-label");
      if (label)
        tags.push(label.textContent || "");
    });
    return tags;
  }
  async addTagFromInput() {
    const raw = this.tagInputEl.value.trim();
    if (!raw)
      return;
    const parts = raw.split(",").map((s) => s.trim().replace(/^#/, "")).filter(Boolean);
    if (parts.length === 0)
      return;
    this.tagInputEl.value = "";
    for (const tag of parts) {
      await this.addSingleTag(tag);
    }
  }
  async addSingleTag(tag) {
    if (this.selected.size === 0)
      return;
    for (const p of this.selected) {
      const existing = this.plugin.getItemTags(p);
      if (existing.includes(tag))
        continue;
      await this.plugin.setItemTags(p, [...existing, tag]);
      const item = this.items.find((i) => i.path === p);
      if (item)
        item.tags = this.plugin.getItemTags(p);
    }
    this.buildTagFreq();
    this.render();
    this.renderTagChipsFromSelection();
  }
  async removeTagAndSave(tag) {
    if (this.selected.size === 0)
      return;
    for (const p of this.selected) {
      const existing = this.plugin.getItemTags(p);
      const updated = existing.filter((t2) => t2 !== tag);
      await this.plugin.setItemTags(p, updated);
      const item = this.items.find((i) => i.path === p);
      if (item)
        item.tags = this.plugin.getItemTags(p);
    }
    this.buildTagFreq();
    this.render();
    this.renderTagChipsFromSelection();
  }
  renderTagChipsFromSelection() {
    if (this.selected.size === 0) {
      this.tagBarEl.addClass("masonry-hide");
      return;
    }
    this.tagBarEl.removeClass("masonry-hide");
    const allTags = /* @__PURE__ */ new Set();
    for (const p of this.selected) {
      for (const t2 of this.plugin.getItemTags(p))
        allTags.add(t2);
    }
    this.tagChipsEl.empty();
    const sorted = [...allTags].sort();
    for (const tag of sorted) {
      const chip = this.tagChipsEl.createSpan({ cls: "masonry-chip" });
      chip.createSpan({ cls: "masonry-chip-label", text: `#${tag}` });
      const del = chip.createSpan({ cls: "masonry-chip-x", text: "\xD7" });
      del.addEventListener("click", (e) => {
        e.stopPropagation();
        void this.removeTagAndSave(tag);
      });
    }
  }
  focusTagInput() {
    this.renderTagChipsFromSelection();
    this.tagInputEl.focus();
  }
  // ── tag cloud ───────────────────────────────────────────
  toggleTagCloud() {
    if (this.tagCloudVisible()) {
      this.tagCloudEl.addClass("masonry-hide");
    } else {
      this.buildTagCloud();
      this.tagCloudEl.removeClass("masonry-hide");
      window.setTimeout(() => {
        const doc = activeDocument;
        const handler = (e) => {
          if (!this.tagCloudEl.contains(e.target) && e.target !== this.tagCloudBtnEl) {
            this.tagCloudEl.addClass("masonry-hide");
            doc.removeEventListener("click", handler);
          }
        };
        doc.addEventListener("click", handler);
      }, 0);
    }
  }
  tagCloudVisible() {
    return !this.tagCloudEl.hasClass("masonry-hide");
  }
  buildTagFreq() {
    if (!this.plugin.settings.fileTags)
      return;
    this.tagFreq.clear();
    for (const item of this.items) {
      if (item.isFolder)
        continue;
      const tags = this.plugin.getItemTags(item.path);
      for (const t2 of tags) {
        this.tagFreq.set(t2, (this.tagFreq.get(t2) || 0) + 1);
      }
    }
  }
  buildTagCloud() {
    this.tagCloudEl.empty();
    this.tagCloudEl.createDiv({ cls: "masonry-tc-title", text: t("label.tagCloud") });
    const list = this.tagCloudEl.createDiv({ cls: "masonry-tc-items" });
    const sorted = [...this.tagFreq.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
    if (sorted.length === 0) {
      list.createSpan({ cls: "masonry-tc-empty", text: t("label.noTags") });
    }
    const maxFreq = sorted.length > 0 ? sorted[0][1] : 1;
    for (const [tag, freq] of sorted) {
      const el = list.createSpan({ cls: "masonry-tc-tag" });
      el.setText(`#${tag} (${freq})`);
      const scale = 0.75 + freq / maxFreq * 0.5;
      el.style.fontSize = `${scale}em`;
      el.addEventListener("click", () => {
        this.searchEl.value = tag;
        this.searchQuery = tag;
        this.tagCloudEl.addClass("masonry-hide");
        this.render();
      });
    }
  }
  // ── navigation ──────────────────────────────────────────
  async loadFolder(path) {
    this.isBoardView = false;
    this.boardFile = null;
    this.editBoardBtnEl.addClass("masonry-hide");
    if (this.historyIdx === -1 || this.history[this.historyIdx] !== path) {
      this.history = this.history.slice(0, this.historyIdx + 1);
      this.history.push(path);
      this.historyIdx = this.history.length - 1;
    }
    this.currentPath = path;
    this.selected.clear();
    this.tagBarEl.addClass("masonry-hide");
    this.tagCloudEl.addClass("masonry-hide");
    this.updateUI();
    const folder = this.app.vault.getAbstractFileByPath(path);
    if (!folder || !(folder instanceof import_obsidian3.TFolder)) {
      new import_obsidian3.Notice(t("notice.folderNotFound"));
      return;
    }
    this.items = [];
    for (const child of folder.children) {
      const item = await this.toFileItem(child);
      if (item)
        this.items.push(item);
    }
    await this.enrichItems(this.items);
    this.buildTagFreq();
    this.render();
  }
  async loadPinBoard(file) {
    this.isBoardView = true;
    this.boardFile = file;
    this.editBoardBtnEl.removeClass("masonry-hide");
    const boardPath = file.path;
    if (this.historyIdx === -1 || this.history[this.historyIdx] !== boardPath) {
      this.history = this.history.slice(0, this.historyIdx + 1);
      this.history.push(boardPath);
      this.historyIdx = this.history.length - 1;
    }
    this.currentPath = boardPath;
    this.selected.clear();
    this.tagBarEl.addClass("masonry-hide");
    this.tagCloudEl.addClass("masonry-hide");
    this.updateUI();
    const pins = await this.plugin.getPinBoardPins(file);
    this.items = [];
    for (const pinPath of pins) {
      const abs = this.app.vault.getAbstractFileByPath(pinPath);
      if (abs instanceof import_obsidian3.TFolder) {
        this.items.push({ path: abs.path, name: abs.name, type: "folder", isFolder: true, tags: this.plugin.getItemTags(abs.path) });
      } else if (abs instanceof import_obsidian3.TFile) {
        const item = await this.toFileItem(abs);
        if (item) {
          item.tags = this.plugin.getItemTags(abs.path);
          this.items.push(item);
        }
      }
    }
    await this.enrichItems(this.items);
    this.buildTagFreq();
    this.render();
  }
  async editCurrentBoard() {
    var _a;
    if (this.boardFile) {
      const leaf = (_a = this.app.workspace.getMostRecentLeaf()) != null ? _a : this.app.workspace.getLeaf();
      await leaf.openFile(this.boardFile);
    }
  }
  goBack() {
    if (this.historyIdx > 0) {
      this.historyIdx--;
      this.currentPath = this.history[this.historyIdx];
      this.selected.clear();
      this.updateUI();
      void this.loadFolderOrBoard(this.currentPath);
    }
  }
  goForward() {
    if (this.historyIdx < this.history.length - 1) {
      this.historyIdx++;
      this.currentPath = this.history[this.historyIdx];
      this.selected.clear();
      this.updateUI();
      void this.loadFolderOrBoard(this.currentPath);
    }
  }
  updateUI() {
    if (this.isBoardView && this.boardFile) {
      this.pathEl.setText(this.boardFile.name.replace(/\.md$/i, ""));
    } else {
      this.pathEl.setText(this.currentPath || "/");
    }
    this.backBtn.toggleClass("masonry-nav-disabled", this.historyIdx <= 0);
    this.fwdBtn.toggleClass("masonry-nav-disabled", this.historyIdx >= this.history.length - 1);
  }
  // ── file-item conversion ────────────────────────────────
  async toFileItem(file) {
    if (file instanceof import_obsidian3.TFolder) {
      return { path: file.path, name: file.name, type: "folder", isFolder: true, tags: this.plugin.getItemTags(file.path) };
    }
    if (!(file instanceof import_obsidian3.TFile))
      return null;
    const ext = file.extension.toLowerCase();
    const isImage = IMAGE_EXTS.has(ext);
    const type = isImage ? "image" : ext === "md" ? "note" : "other";
    return {
      path: file.path,
      name: file.name,
      type,
      isFolder: false,
      extension: ext,
      tags: this.plugin.getItemTags(file.path)
    };
  }
  async enrichItems(items) {
    await Promise.all(items.map(async (item) => {
      if (item.type === "note" && !item.notePreview) {
        item.notePreview = await this.getNotePreview(item.path);
      }
      if (item.isFolder && !item.folderThumb) {
        item.folderThumb = await this.getFolderThumb(item.path);
      }
    }));
  }
  async getNotePreview(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (!(file instanceof import_obsidian3.TFile))
      return "";
    try {
      const content = await this.app.vault.read(file);
      const body = content.replace(/^---[\s\S]*?---\n*/m, "");
      const lines = body.split("\n").filter((l) => l.trim());
      let preview = lines.slice(0, 30).join("\n").trim();
      preview = preview.replace(/!\[.*?\]\(.*?\)/g, "").trim();
      if (preview.length > 2e3)
        preview = preview.slice(0, 1997) + "\u2026";
      return preview || "";
    } catch (e) {
      return "";
    }
  }
  async getFolderThumb(path) {
    const folder = this.app.vault.getAbstractFileByPath(path);
    if (!(folder instanceof import_obsidian3.TFolder))
      return void 0;
    for (const child of folder.children) {
      if (child instanceof import_obsidian3.TFile && IMAGE_EXTS.has(child.extension.toLowerCase()))
        return child.path;
    }
    return void 0;
  }
  getResourcePath(filePath) {
    const file = this.app.vault.getAbstractFileByPath(filePath);
    return file instanceof import_obsidian3.TFile ? this.app.vault.getResourcePath(file) : "";
  }
  // ── rendering ───────────────────────────────────────────
  render() {
    var _a, _b, _c, _d, _e, _f;
    this.gridWrapper.empty();
    const q = this.searchQuery.toLowerCase().trim();
    let folders = this.items.filter((i) => i.isFolder).sort((a, b) => a.name.localeCompare(b.name));
    let files = this.items.filter((i) => !i.isFolder).sort((a, b) => a.name.localeCompare(b.name));
    if (q) {
      const match = (i) => i.name.toLowerCase().includes(q) || i.tags.some((t2) => t2.toLowerCase().includes(q));
      folders = folders.filter(match);
      files = files.filter(match);
    }
    const gap = (_a = this.plugin.settings.itemGap) != null ? _a : 10;
    const colCount = (_b = this.plugin.settings.columnCount) != null ? _b : 4;
    const noteMinH = (_c = this.plugin.settings.noteCardMinHeight) != null ? _c : 100;
    const noteMaxH = (_d = this.plugin.settings.noteCardMaxHeight) != null ? _d : 500;
    const noteFontSize = (_e = this.plugin.settings.noteCardFontSize) != null ? _e : 14;
    const folderCount = (_f = this.plugin.settings.folderCount) != null ? _f : 8;
    this.gridWrapper.style.setProperty("--masonry-gap", `${gap}px`);
    this.gridWrapper.style.setProperty("--masonry-note-min-height", `${noteMinH + 8}px`);
    this.gridWrapper.style.setProperty("--masonry-note-max-height", `${noteMaxH + 8}px`);
    this.gridWrapper.style.setProperty("--masonry-note-font-size", `${noteFontSize}px`);
    const hasSections = [];
    const rowItems = this.isBoardView ? [] : folders;
    if (rowItems.length > 0) {
      hasSections.push("folders");
      const row = this.gridWrapper.createDiv({ cls: "masonry-folders-row" });
      row.style.setProperty("--masonry-folder-count", String(folderCount));
      row.style.gap = `${gap}px`;
      for (const item of rowItems) {
        this.createCardIn(row, item);
      }
    }
    const notes = files.filter((i) => i.type === "note");
    if (notes.length > 0) {
      hasSections.push("notes");
      const grid = this.gridWrapper.createDiv({ cls: "masonry-grid masonry-grid-notes" });
      grid.style.marginTop = `${gap}px`;
      const cols = [];
      for (let i = 0; i < colCount; i++)
        cols.push(grid.createDiv({ cls: "masonry-col" }));
      notes.forEach((item, idx) => this.createCardIn(cols[idx % colCount], item));
    }
    const others = files.filter((i) => i.type !== "note");
    if (others.length > 0) {
      hasSections.push("others");
      const grid = this.gridWrapper.createDiv({ cls: "masonry-grid masonry-grid-others" });
      grid.style.marginTop = `${gap}px`;
      const cols = [];
      for (let i = 0; i < colCount; i++)
        cols.push(grid.createDiv({ cls: "masonry-col" }));
      others.forEach((item, idx) => this.createCardIn(cols[idx % colCount], item));
    }
    if (hasSections.length === 0) {
      this.gridWrapper.createDiv({ cls: "masonry-empty" }).setText(q ? t("notice.noMatch") : this.isBoardView ? t("notice.boardEmpty") : t("notice.folderEmpty"));
    }
  }
  // create a card and attach all event listeners
  createCardIn(parent, item) {
    const card = parent.createDiv({
      cls: `masonry-card ${item.isFolder ? "masonry-folder" : ""} ${this.selected.has(item.path) ? "masonry-selected" : ""}`,
      attr: { draggable: "true", "data-path": item.path }
    });
    this.buildCardContent(card, item);
    card.addEventListener("click", (e) => {
      if (e.ctrlKey || e.metaKey) {
        this.toggleSelect(item.path, card);
      } else if (e.shiftKey && this.lastSelectedEl) {
        this.rangeSelect(card);
      } else {
        this.clearSelection();
        this.selected.add(item.path);
        card.addClass("masonry-selected");
        this.lastSelectedEl = card;
      }
      this.renderTagChipsFromSelection();
    });
    card.addEventListener("dblclick", () => {
      void this.openItem(item);
    });
    card.addEventListener("dragstart", (e) => {
      var _a, _b;
      const dragPaths = this.selected.has(item.path) && this.selected.size > 1 ? [...this.selected] : [item.path];
      (_a = e.dataTransfer) == null ? void 0 : _a.setData("text/plain", item.path);
      (_b = e.dataTransfer) == null ? void 0 : _b.setData("text/x-masonry-items", JSON.stringify(dragPaths));
      e.dataTransfer.effectAllowed = "move";
      card.addClass("masonry-dragging");
    });
    card.addEventListener("dragend", () => card.removeClass("masonry-dragging"));
    card.addEventListener("contextmenu", (e) => {
      e.preventDefault();
      if (!this.selected.has(item.path)) {
        this.clearSelection();
        this.selected.add(item.path);
        card.addClass("masonry-selected");
      }
      this.showCtxMenu(e, item);
    });
    return card;
  }
  buildCardContent(card, item) {
    const showNames = this.plugin.settings.showFileNames;
    const showTags = this.plugin.settings.showTags;
    if (item.isFolder) {
      card.addClass("masonry-folder-card");
      this.buildCardHeader(card, "folder", item.name);
      if (item.folderThumb) {
        const thumb = card.createDiv({ cls: "masonry-thumb" });
        const src = this.getResourcePath(item.folderThumb);
        if (src) {
          thumb.createEl("img", { cls: "masonry-img", attr: { src, loading: "lazy" } });
        }
      }
    } else if (item.type === "note") {
      card.addClass("masonry-note-card");
      const displayName = item.extension === "md" ? item.name.replace(/\.md$/i, "") : item.name;
      this.buildCardHeader(card, "document", displayName);
      const thumb = card.createDiv({ cls: "masonry-thumb" });
      if (item.notePreview) {
        const previewEl = thumb.createDiv({ cls: "masonry-note-preview" });
        void import_obsidian3.MarkdownRenderer.render(this.app, item.notePreview, previewEl, item.path, this);
      } else {
        thumb.createDiv({ cls: "masonry-note-preview masonry-note-empty", text: t("label.emptyNote") });
      }
    } else {
      const thumb = card.createDiv({ cls: "masonry-thumb" });
      if (item.type === "image") {
        const src = this.getResourcePath(item.path);
        if (src) {
          const img = thumb.createEl("img", { cls: "masonry-img", attr: { src, loading: "lazy" } });
          img.onerror = () => img.replaceWith(createDiv({ cls: "masonry-placeholder", text: "\u{1F5BC}" }));
        }
      } else {
        thumb.createDiv({ cls: "masonry-placeholder", text: "\u{1F4C4}" });
      }
      if (showNames) {
        const label = card.createDiv({ cls: "masonry-label" });
        label.setText(item.name);
      }
    }
    if (showTags && (item.type === "note" || item.tags.length > 0)) {
      const tagsEl = card.createDiv({ cls: "masonry-tags" });
      for (const t2 of item.tags.slice(0, 5)) {
        tagsEl.createSpan({ cls: "masonry-tag", text: `#${t2}` });
      }
      if (item.tags.length > 5)
        tagsEl.createSpan({ cls: "masonry-tag-more", text: `+${item.tags.length - 5}` });
    }
  }
  buildCardHeader(card, iconId, name) {
    const header = card.createDiv({ cls: "masonry-item-header" });
    const iconEl = header.createDiv({ cls: "masonry-item-icon" });
    (0, import_obsidian3.setIcon)(iconEl, iconId);
    header.createSpan({ cls: "masonry-item-name", text: name });
    return header;
  }
  // ── selection ───────────────────────────────────────────
  clearSelection() {
    this.selected.clear();
    this.gridWrapper.querySelectorAll(".masonry-selected").forEach((el) => el.removeClass("masonry-selected"));
    this.lastSelectedEl = null;
  }
  toggleSelect(path, card) {
    if (this.selected.has(path)) {
      this.selected.delete(path);
      card.removeClass("masonry-selected");
    } else {
      this.selected.add(path);
      card.addClass("masonry-selected");
      this.lastSelectedEl = card;
    }
  }
  rangeSelect(card) {
    const allCards = Array.from(this.gridWrapper.querySelectorAll(".masonry-card"));
    const si = allCards.indexOf(this.lastSelectedEl);
    const ei = allCards.indexOf(card);
    if (si === -1 || ei === -1)
      return;
    const [lo, hi] = si < ei ? [si, ei] : [ei, si];
    for (let i = lo; i <= hi; i++) {
      const c = allCards[i];
      const p = c.getAttr("data-path");
      if (p) {
        this.selected.add(p);
        c.addClass("masonry-selected");
      }
    }
  }
  // ── item actions ────────────────────────────────────────
  async openItem(item) {
    var _a;
    if (item.isFolder) {
      await this.loadFolderOrBoard(item.path);
      return;
    }
    const file = this.app.vault.getAbstractFileByPath(item.path);
    if (!file || !(file instanceof import_obsidian3.TFile))
      return;
    if (item.type === "image") {
      const images = this.items.filter((i) => i.type === "image");
      const idx = images.findIndex((i) => i.path === item.path);
      new ImageViewModal(this.app, this.plugin, images, idx >= 0 ? idx : 0, this.boardFile).open();
    } else {
      const leaf = (_a = this.app.workspace.getMostRecentLeaf()) != null ? _a : this.app.workspace.getLeaf();
      await leaf.openFile(file);
    }
  }
  async deleteSelected(permanent) {
    if (this.selected.size === 0)
      return;
    if (this.isBoardView && this.boardFile) {
      const removed = new Set(this.selected);
      for (const p of this.selected) {
        await this.app.fileManager.processFrontMatter(this.boardFile, (fm) => {
          const data = fm;
          if (Array.isArray(data.pins)) {
            data.pins = data.pins.filter((pin) => pin !== p);
          }
        });
      }
      new import_obsidian3.Notice(t("notice.pinsRemoved", { count: removed.size }));
      this.selected.clear();
      await this.loadPinBoard(this.boardFile);
      return;
    }
    for (const p of this.selected) {
      const file = this.app.vault.getAbstractFileByPath(p);
      if (!file)
        continue;
      try {
        if (file instanceof import_obsidian3.TFile)
          await this.app.fileManager.trashFile(file);
      } catch (e) {
        console.error("Failed to delete", p, e);
      }
    }
    const count = this.selected.size;
    this.selected.clear();
    this.tagBarEl.addClass("masonry-hide");
    new import_obsidian3.Notice(permanent ? t("notice.permanentDeleted", { count }) : t("notice.movedToTrash", { count }));
    await this.loadFolderOrBoard(this.currentPath);
  }
  async pinItem(filePath) {
    this.selected.add(filePath);
    await this.showPinModal();
  }
  async showPinModal() {
    if (this.selected.size === 0) {
      new import_obsidian3.Notice(t("notice.selectFirst"));
      return;
    }
    const boards = this.plugin.getPinBoards();
    if (boards.length === 0) {
      new import_obsidian3.Notice(t("notice.noBoards"));
      return;
    }
    new PinSelectModal(this.app, this.plugin, boards, [...this.selected]).open();
  }
  showCtxMenu(e, item) {
    const menu = new import_obsidian3.Menu();
    menu.addItem((i) => i.setTitle(t("menu.open")).setIcon("document").onClick(() => this.openItem(item)));
    menu.addItem((i) => i.setTitle(t("menu.pinToBoardShort")).setIcon("pin").onClick(async () => {
      this.selected.add(item.path);
      await this.showPinModal();
    }));
    menu.addItem((i) => i.setTitle(t("menu.assignTags")).setIcon("tag").onClick(() => {
      if (!this.selected.has(item.path)) {
        this.selected.add(item.path);
      }
      this.focusTagInput();
    }));
    menu.addSeparator();
    if (this.isBoardView) {
      menu.addItem((i) => i.setTitle(t("menu.removeFromBoard")).setIcon("trash").onClick(async () => {
        this.selected.add(item.path);
        await this.deleteSelected(false);
      }));
    } else {
      menu.addItem((i) => i.setTitle(t("menu.delete")).setIcon("trash").onClick(() => {
        this.selected.add(item.path);
        void this.deleteSelected(false);
      }));
    }
    menu.showAtMouseEvent(e);
  }
  // ── drag & drop ─────────────────────────────────────────
  async handleDropOnFolder(srcPath, destPath) {
    const destFile = this.app.vault.getAbstractFileByPath(destPath);
    if (destFile instanceof import_obsidian3.TFile) {
      if (this.plugin.isPinBoard(destFile)) {
        await this.plugin.addToPinBoard(srcPath, destFile);
        new import_obsidian3.Notice(t("notice.pinned", { name: destFile.name.replace(/\.md$/i, "") }));
        return;
      }
    }
    if (destFile instanceof import_obsidian3.TFolder) {
      const srcName = srcPath.split("/").pop();
      if (!srcName)
        return;
      const srcFile = this.app.vault.getAbstractFileByPath(srcPath);
      if (!srcFile)
        return;
      try {
        await this.app.fileManager.renameFile(srcFile, `${destPath}/${srcName}`);
      } catch (e) {
        new import_obsidian3.Notice(t("notice.moveFailed"));
      }
    }
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  masonryFolders: [],
  showFileNames: true,
  showTags: true,
  fileTags: {},
  itemGap: 10,
  columnCount: 4,
  noteCardMinHeight: 100,
  noteCardMaxHeight: 500,
  noteCardFontSize: 14,
  folderCount: 8
};
var ObsidianMasonryPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this._openingBoard = false;
    this.injectedStyleEl = null;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_MASONRY, (leaf) => new MasonryView(leaf, this));
    this.app.workspace.onLayoutReady(() => this.updatePinBoardStyles());
    this.addCommand({
      id: "open-masonry-view",
      name: t("cmd.openMasonryView"),
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (file == null ? void 0 : file.parent) {
          if (!checking)
            void this.openMasonryView(file.parent.path);
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "toggle-masonry-folder",
      name: t("cmd.toggleMasonryFolder"),
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (file == null ? void 0 : file.parent) {
          if (!checking)
            void this.toggleMasonryFolder(file.parent.path);
          return true;
        }
        return false;
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-open", async (file) => {
        if (this._openingBoard)
          return;
        if (!file || file.extension !== "md")
          return;
        if (this.isPinBoard(file)) {
          this._openingBoard = true;
          await this.openMasonryView(file.path);
          window.setTimeout(() => {
            this._openingBoard = false;
          }, 500);
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian4.TFolder) {
          const isEnabled = this.settings.masonryFolders.includes(file.path);
          menu.addItem((item) => {
            item.setTitle(isEnabled ? t("menu.disableMasonry") : t("menu.enableMasonry")).setIcon("grid").onClick(async () => await this.toggleMasonryFolder(file.path));
          });
          menu.addItem((item) => {
            item.setTitle(t("menu.openMasonry")).setIcon("grid-3x3").onClick(async () => await this.openMasonryView(file.path));
          });
          menu.addSeparator();
          menu.addItem((item) => {
            item.setTitle(t("menu.createPinBoard")).setIcon("pin").onClick(async () => {
              const name = file.name + " Board";
              const board = await this.createPinBoard(name, file.path);
              if (board) {
                new import_obsidian4.Notice(t("notice.boardCreated", { name }));
                this._openingBoard = true;
                await this.openMasonryView(board.path);
                window.setTimeout(() => {
                  this._openingBoard = false;
                }, 500);
              }
            });
          });
        }
        if (file instanceof import_obsidian4.TFile) {
          menu.addItem((item) => {
            item.setTitle(t("menu.pinToBoard")).setIcon("pin").onClick(async () => {
              const boards = this.getPinBoards();
              new PinSelectModal(this.app, this, boards, [file.path]).open();
            });
          });
        }
      })
    );
    this.registerEvent(
      this.app.metadataCache.on("resolved", () => this.updatePinBoardStyles())
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => this.handleRename(file, oldPath))
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => this.handleDelete(file))
    );
    this.addSettingTab(new MasonrySettingTab(this.app, this));
    const doc = activeDocument;
    let lastClickPath = "";
    let lastClickTime = 0;
    this.registerDomEvent(doc, "click", (e) => {
      var _a;
      if (e.button !== 0)
        return;
      const content = (_a = e.target) == null ? void 0 : _a.closest(".nav-folder-title-content");
      if (!content)
        return;
      const title = content.closest(".nav-folder-title");
      if (!title)
        return;
      const path = title.getAttr("data-path");
      if (!path || !this.settings.masonryFolders.includes(path))
        return;
      const now = Date.now();
      if (path === lastClickPath && now - lastClickTime < 400) {
        lastClickPath = "";
        lastClickTime = 0;
        return;
      }
      lastClickPath = path;
      lastClickTime = now;
      e.preventDefault();
      e.stopPropagation();
      void this.openMasonryView(path);
    }, true);
  }
  onunload() {
    if (this.injectedStyleEl) {
      this.injectedStyleEl.remove();
    }
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async toggleMasonryFolder(path) {
    const idx = this.settings.masonryFolders.indexOf(path);
    if (idx > -1) {
      this.settings.masonryFolders.splice(idx, 1);
      new import_obsidian4.Notice(t("notice.masonryDisabled", { path }));
    } else {
      this.settings.masonryFolders.push(path);
      new import_obsidian4.Notice(t("notice.masonryEnabled", { path }));
    }
    await this.saveSettings();
    this.updatePinBoardStyles();
  }
  async openMasonryView(folderOrBoardPath) {
    const path = folderOrBoardPath || "/";
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_MASONRY);
    if (leaves.length > 0) {
      void this.app.workspace.revealLeaf(leaves[0]);
      if (leaves[0].view instanceof MasonryView) {
        await leaves[0].view.loadFolderOrBoard(path);
      }
      return;
    }
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.setViewState({
      type: VIEW_TYPE_MASONRY,
      active: true,
      state: { folderPath: path }
    });
    void this.app.workspace.revealLeaf(leaf);
  }
  // ── pin boards ─────────────────────────────────────────
  isPinBoard(file) {
    const cache = this.app.metadataCache.getFileCache(file);
    const fm = cache == null ? void 0 : cache.frontmatter;
    const tags = fm == null ? void 0 : fm.tags;
    return Array.isArray(tags) && tags.includes("pin-board") || typeof tags === "string" && tags === "pin-board";
  }
  getPinBoards() {
    return this.app.vault.getMarkdownFiles().filter((f) => this.isPinBoard(f));
  }
  async createPinBoard(name, folderPath) {
    const safeName = name.replace(/[\\/:*?"<>|]/g, "_");
    let fileName = `${safeName}.md`;
    let path = folderPath ? `${folderPath}/${fileName}` : fileName;
    let counter = 1;
    while (await this.app.vault.adapter.exists(path)) {
      fileName = `${safeName} ${counter}.md`;
      path = folderPath ? `${folderPath}/${fileName}` : fileName;
      counter++;
    }
    try {
      const file = await this.app.vault.create(
        path,
        `---
tags:
  - pin-board
pins: []
---

# ${name}

Your pinned items will appear here.
`
      );
      this.updatePinBoardStyles();
      return file;
    } catch (e) {
      new import_obsidian4.Notice(t("notice.createBoardFailed"));
      return null;
    }
  }
  updatePinBoardStyles() {
    if (!this.injectedStyleEl) {
      const doc = activeDocument;
      this.injectedStyleEl = doc.createElement("style");
      this.injectedStyleEl.setAttr("data-masonry-icons", "");
      doc.head.appendChild(this.injectedStyleEl);
    }
    let css = "";
    const pinSvg = `data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' stroke='white' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' fill='none'%3E%3Cline x1='12' y1='17' x2='12' y2='22' stroke='white'/%3E%3Cpath d='M5 17h14v-1.76a2 2 0 0 0-1.11-1.79l-1.78-.9A2 2 0 0 1 15 10.76V6h1a2 2 0 0 0 0-4H8a2 2 0 0 0 0 4h1v4.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24Z'/%3E%3C/svg%3E`;
    for (const b of this.getPinBoards()) {
      const safePath = b.path.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
      css += `.nav-file-title[data-path="${safePath}"] .nav-file-title-content::before{content:"";display:inline-block;width:1.2em;height:1.2em;margin-right:0.15em;vertical-align:middle;background-color:currentColor;-webkit-mask:url("${pinSvg}") no-repeat center;mask:url("${pinSvg}") no-repeat center;-webkit-mask-size:contain;mask-size:contain}`;
    }
    const gridSvg = `data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'%3E%3Crect x='3' y='3' width='8' height='8' rx='1' fill='white'/%3E%3Crect x='13' y='3' width='8' height='8' rx='1' fill='white'/%3E%3Crect x='3' y='13' width='8' height='8' rx='1' fill='white'/%3E%3Crect x='13' y='13' width='8' height='8' rx='1' fill='white'/%3E%3C/svg%3E`;
    for (const fp of this.settings.masonryFolders) {
      const safePath = fp.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
      css += `.nav-folder-title[data-path="${safePath}"] .nav-folder-title-content::before{content:"";display:inline-block;width:1.2em;height:1.2em;margin-right:0.15em;vertical-align:middle;background-color:currentColor;-webkit-mask:url("${gridSvg}") no-repeat center;mask:url("${gridSvg}") no-repeat center;-webkit-mask-size:contain;mask-size:contain}`;
    }
    this.injectedStyleEl.textContent = css;
  }
  // update pin-board pins when files/folders are renamed/moved
  async handleRename(file, oldPath) {
    const newPath = file.path;
    const boards = this.getPinBoards();
    let needRefresh = false;
    for (const board of boards) {
      let changed = false;
      await this.app.fileManager.processFrontMatter(board, (fm) => {
        const data = fm;
        if (!Array.isArray(data.pins))
          return;
        const updated = data.pins.map((p) => {
          if (p === oldPath) {
            changed = true;
            return newPath;
          }
          if (p.startsWith(oldPath + "/")) {
            changed = true;
            return newPath + "/" + p.slice(oldPath.length + 1);
          }
          return p;
        });
        if (changed)
          data.pins = updated;
      });
      if (changed) {
        needRefresh = true;
        for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_MASONRY)) {
          if (leaf.view instanceof MasonryView && leaf.view.currentPath === board.path) {
            await leaf.view.loadFolderOrBoard(board.path);
          }
        }
      }
    }
    if (needRefresh)
      this.updatePinBoardStyles();
  }
  // remove deleted files/folders from all pin-board pins
  async handleDelete(file) {
    const path = file.path;
    const boards = this.getPinBoards();
    let needRefresh = false;
    for (const board of boards) {
      let changed = false;
      await this.app.fileManager.processFrontMatter(board, (fm) => {
        const data = fm;
        if (!Array.isArray(data.pins))
          return;
        const filtered = data.pins.filter((p) => {
          if (p === path || p.startsWith(path + "/")) {
            changed = true;
            return false;
          }
          return true;
        });
        if (changed)
          data.pins = filtered;
      });
      if (changed) {
        needRefresh = true;
        for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_MASONRY)) {
          if (leaf.view instanceof MasonryView && leaf.view.currentPath === board.path) {
            await leaf.view.loadFolderOrBoard(board.path);
          }
        }
      }
    }
    if (needRefresh)
      this.updatePinBoardStyles();
  }
  // normalise any path (absolute, relative, name-only) to a vault-relative path
  toVaultRelativePath(p) {
    var _a, _b;
    const clean = p.replace(/\\/g, "/").trim();
    const tryPath = (path) => {
      const file = this.app.vault.getAbstractFileByPath(path);
      return file ? file.path : null;
    };
    let found = tryPath(clean);
    if (found)
      return found;
    if (!clean.match(/\.\w+$/)) {
      found = tryPath(clean + ".md");
      if (found)
        return found;
    }
    try {
      const vaultPath = ((_b = (_a = this.app.vault.adapter).getFullPath) == null ? void 0 : _b.call(_a, "/")) || "";
      const norm = String(vaultPath).replace(/\\/g, "/").replace(/\/$/, "");
      if (norm && clean.startsWith(norm + "/")) {
        const rel = clean.slice(norm.length + 1);
        found = tryPath(rel);
        if (found)
          return found;
        if (!rel.match(/\.\w+$/)) {
          found = tryPath(rel + ".md");
          if (found)
            return found;
        }
      }
    } catch (e) {
    }
    const name = clean.split("/").pop() || "";
    const all = this.app.vault.getAllLoadedFiles();
    const byName = all.filter((f) => f.name === name);
    if (byName.length === 1)
      return byName[0].path;
    if (!name.match(/\.\w+$/)) {
      const byNameMd = all.filter((f) => f.name === name + ".md");
      if (byNameMd.length === 1)
        return byNameMd[0].path;
    }
    const bySuffix = all.filter((f) => f.path.endsWith("/" + name));
    if (bySuffix.length === 1)
      return bySuffix[0].path;
    return clean;
  }
  async addToPinBoard(filePath, board) {
    const normalized = this.toVaultRelativePath(filePath);
    await this.app.fileManager.processFrontMatter(board, (fm) => {
      const data = fm;
      if (!Array.isArray(data.pins))
        data.pins = [];
      const pins = data.pins;
      if (!pins.includes(normalized))
        pins.push(normalized);
    });
  }
  async getPinBoardPins(board) {
    const content = await this.app.vault.read(board);
    const pins = this.parsePinsFromYaml(content);
    return pins.map((p) => this.toVaultRelativePath(p));
  }
  parsePinsFromYaml(content) {
    const fmMatch = content.match(/^---\n([\s\S]*?)\n(?:---|\.\.\.)/);
    if (!fmMatch)
      return [];
    const yaml = fmMatch[1];
    const inline = yaml.match(/^pins:\s*\[(.*?)\]\s*$/m);
    if (inline)
      return inline[1].split(",").map((s) => s.trim().replace(/['"]/g, "")).filter(Boolean);
    if (/^pins:\s*$/m.test(yaml)) {
      const lines = yaml.split("\n");
      const start = lines.findIndex((l) => /^pins:\s*$/.test(l));
      if (start === -1)
        return [];
      const items = [];
      for (let i = start + 1; i < lines.length; i++) {
        const item = lines[i].match(/^\s+-\s+(.+)$/);
        if (item)
          items.push(item[1].trim().replace(/['"]/g, ""));
        else if (lines[i].trim() && !/^\s/.test(lines[i]))
          break;
      }
      return items;
    }
    const single = yaml.match(/^pins:\s+(.+)$/m);
    if (single)
      return [single[1].trim().replace(/['"]/g, "")];
    return [];
  }
  // ── tag storage (plugin data for all files) ─────────────
  getItemTags(filePath) {
    var _a, _b;
    return (_b = (_a = this.settings.fileTags) == null ? void 0 : _a[filePath]) != null ? _b : [];
  }
  async setItemTags(filePath, tags) {
    if (!this.settings.fileTags)
      this.settings.fileTags = {};
    if (tags.length === 0) {
      delete this.settings.fileTags[filePath];
    } else {
      this.settings.fileTags[filePath] = [...tags];
    }
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (file instanceof import_obsidian4.TFile && file.extension === "md") {
      try {
        await this.app.fileManager.processFrontMatter(file, (fm) => {
          const data = fm;
          data.tags = tags.length > 0 ? [...tags] : void 0;
        });
      } catch (e) {
      }
    }
    await this.saveSettings();
  }
};
var MasonrySettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian4.Setting(containerEl).setName(t("sett.heading")).setDesc(t("sett.desc")).setHeading();
    new import_obsidian4.Setting(containerEl).setName(t("sett.showNames")).setDesc(t("sett.showNamesDesc")).addToggle((c) => c.setValue(this.plugin.settings.showFileNames).onChange(async (v) => {
      this.plugin.settings.showFileNames = v;
      await this.plugin.saveSettings();
      this.refreshMasonryViews();
    }));
    new import_obsidian4.Setting(containerEl).setName(t("sett.showTags")).setDesc(t("sett.showTagsDesc")).addToggle((c) => c.setValue(this.plugin.settings.showTags).onChange(async (v) => {
      this.plugin.settings.showTags = v;
      await this.plugin.saveSettings();
      this.refreshMasonryViews();
    }));
    new import_obsidian4.Setting(containerEl).setName(t("sett.gap")).setDesc(t("sett.gapDesc")).addText((c) => c.setValue(String(this.plugin.settings.itemGap)).onChange(async (v) => {
      const n = parseInt(v, 10);
      if (!isNaN(n)) {
        this.plugin.settings.itemGap = n;
        await this.plugin.saveSettings();
        this.refreshMasonryViews();
      }
    }));
    new import_obsidian4.Setting(containerEl).setName(t("sett.columns")).setDesc(t("sett.columnsDesc")).addText((c) => c.setValue(String(this.plugin.settings.columnCount)).onChange(async (v) => {
      const n = parseInt(v, 10);
      if (!isNaN(n)) {
        this.plugin.settings.columnCount = n;
        await this.plugin.saveSettings();
        this.refreshMasonryViews();
      }
    }));
    new import_obsidian4.Setting(containerEl).setName(t("sett.noteMinH")).setDesc(t("sett.noteMinHDesc")).addText((c) => c.setValue(String(this.plugin.settings.noteCardMinHeight)).onChange(async (v) => {
      const n = parseInt(v, 10);
      if (!isNaN(n)) {
        this.plugin.settings.noteCardMinHeight = n;
        await this.plugin.saveSettings();
        this.refreshMasonryViews();
      }
    }));
    new import_obsidian4.Setting(containerEl).setName(t("sett.noteMaxH")).setDesc(t("sett.noteMaxHDesc")).addText((c) => c.setValue(String(this.plugin.settings.noteCardMaxHeight)).onChange(async (v) => {
      const n = parseInt(v, 10);
      if (!isNaN(n)) {
        this.plugin.settings.noteCardMaxHeight = n;
        await this.plugin.saveSettings();
        this.refreshMasonryViews();
      }
    }));
    new import_obsidian4.Setting(containerEl).setName(t("sett.noteFontSize")).setDesc(t("sett.noteFontSizeDesc")).addText((c) => c.setValue(String(this.plugin.settings.noteCardFontSize)).onChange(async (v) => {
      const n = parseInt(v, 10);
      if (!isNaN(n)) {
        this.plugin.settings.noteCardFontSize = n;
        await this.plugin.saveSettings();
        this.refreshMasonryViews();
      }
    }));
    new import_obsidian4.Setting(containerEl).setName(t("sett.folderCount")).setDesc(t("sett.folderCountDesc")).addText((c) => c.setValue(String(this.plugin.settings.folderCount)).onChange(async (v) => {
      const n = parseInt(v, 10);
      if (!isNaN(n)) {
        this.plugin.settings.folderCount = n;
        await this.plugin.saveSettings();
        this.refreshMasonryViews();
      }
    }));
    const folderSettings = new import_obsidian4.Setting(containerEl).setName(t("sett.masonryFolders"));
    const el = folderSettings.controlEl;
    const list = el.createEl("ul");
    if (this.plugin.settings.masonryFolders.length === 0) {
      list.createEl("li", { text: t("sett.none") });
    } else {
      for (const p of this.plugin.settings.masonryFolders) {
        list.createEl("li", { text: p });
      }
    }
    el.createEl("hr");
    new import_obsidian4.Setting(el).setName(t("sett.clearAssignments")).setDesc(t("sett.clearAssignmentsDesc")).addButton(
      (btn) => btn.setButtonText(t("sett.clearBtn")).setDestructive().onClick(async () => {
        this.plugin.settings.masonryFolders = [];
        await this.plugin.saveSettings();
        list.empty();
        list.createEl("li", { text: t("sett.none") });
        new import_obsidian4.Notice(t("notice.settingsCleared"));
      })
    );
  }
  refreshMasonryViews() {
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_MASONRY)) {
      if (leaf.view instanceof MasonryView)
        leaf.view.render();
    }
  }
};

/* nosourcemap */